version = 0.1

[default.deploy.parameters]
stack_name = "reinvent-sim"
resolve_s3 = true
s3_prefix = "reinvent-sim"
region = "eu-west-1"
profile = "dev"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AllowedOrigin=\"*\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
